name: Soldout
description: "Soldout"
publish_to: 'none'
version: 0.0.1+5

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: 6.1.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  go_router: ^9.0.3
  flutter_screenutil: ^5.6.1
  http: ^1.2.0
  flutter_animate: ^4.2.0+1
  flutter_spinkit: ^5.1.0
  badges: ^3.1.1
  flutter_svg: 2.0.7
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  page_transition: ^2.1.0
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  getwidget: ^4.0.0
  get_it: ^7.6.4
  flutter_native_splash: ^2.3.9
  gap: ^3.0.1
  internet_connection_checker: ^1.0.0+1
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.6
  bloc_test: ^9.1.5
  logger: ^2.0.2+1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/icons/
    # - assets/images/
    # - assets/images/
    # - shorebird.yaml